feat (shortcuts): #43 add custom shortcut management

diff --git a/console/common/core b/console/common/core
--- a/console/common/core
+++ b/console/common/core
@@ -112,13 +112,10 @@ _mod_.replacemod () {
     if echo "$NEW_NAME" | grep -qi ".tasks."; then
       sed -E "s/_mod_\.([a-zA-Z_][a-zA-Z0-9_]*)/${NEW_NAME}.\1/g" "$SOURCE_PATH" > "$PATH_TARGET"
     else
-        NEW_NAME_VAR=$(echo "$NEW_NAME" | sed "s/tasks/props/" | tr "." "_")
-        sed -E "s/_mod_([a-zA-Z_][a-zA-Z0-9_]*)/${NEW_NAME_VAR}_\1/g" "$SOURCE_PATH" > "$PATH_TARGET"
+      NEW_NAME_VAR=$(echo "$NEW_NAME" | sed "s/tasks/props/" | tr "." "_")
+      sed -E "s/_mod_([a-zA-Z_][a-zA-Z0-9_]*)/${NEW_NAME_VAR}_\1/g" "$SOURCE_PATH" > "$PATH_TARGET"
+
     fi
-
-    # translation
-    #sed -i "s/Select an option/hola/g" "$PATH_TARGET"
-
 
     if [ ! $? -eq 0 ]; then
       _mod_.msg_danger "[ERROR] The conversion could not be carried out, report this!" 4
@@ -128,6 +125,10 @@ _mod_.replacemod () {
   fi
 
   source "$PATH_TARGET"
+  # Prepare shortcuts
+  if [[ "$PATH_TARGET" == *".props.shortcuts" ]]; then
+    _mod_.generate_shortcuts_file "${NEW_NAME_VAR}_ITEMS"
+  fi
 
   if [ ! $? -eq 0 ]; then
     _mod_.msg_danger "[ERROR] The resources were not loaded, report this!" 4
@@ -138,30 +139,32 @@ _mod_.replacemod () {
 }
 
 _mod_.generate_shortcuts_file() {
+  local VARIABLE_NAME=$1
   local TARGET_SHORTCUTS="$DIRECTORY_TMP/common.props.shortcuts"
 
-  echo -e "#!/usr/bin/env bash\nset -euo pipefail\n" > "$TARGET_SHORTCUTS"
-  echo "EFDE_SHORTCUTS=(" >> "$TARGET_SHORTCUTS"
+  if [[ ! -f "$TARGET_SHORTCUTS" ]]; then
+    echo -e "#!/usr/bin/env bash\nset -euo pipefail\n" > "$TARGET_SHORTCUTS"
+    echo "EFDE_SHORTCUTS=(" >> "$TARGET_SHORTCUTS"
+  else
+    sed -i '$d' "$TARGET_SHORTCUTS"
+  fi
 
-  for var in $(compgen -A variable); do
-    if [[ "$var" =~ _props_menu_ && "$(declare -p "$var" 2>/dev/null)" =~ "declare -a" ]]; then
-      # shellcheck disable=SC1087
-      eval "ARR=(\"\${$var[@]}\")"
-      for LINE in "${ARR[@]}"; do
-        IFS=',' read -r -a VALUE <<< "$LINE"
+  if [[ "$(declare -p "$VARIABLE_NAME" 2>/dev/null)" =~ "declare -a" ]]; then
+    # shellcheck disable=SC1087
+    eval "ARR=(\"\${$VARIABLE_NAME[@]}\")"
+    for LINE in "${ARR[@]}"; do
+      IFS=',' read -r -a VALUE <<< "$LINE"
 
-        if [[ "${VALUE[0]}" =~ ":" && -n "${VALUE[0]}" && "${VALUE[0]}" != "shortcut:off" ]]; then
-          echo "  \"$LINE\"" >> "$TARGET_SHORTCUTS"
-        fi
-      done
-    fi
-  done
+      echo "  \"$LINE\"" >> "$TARGET_SHORTCUTS"
+    done
+  fi
 
   echo ")" >> "$TARGET_SHORTCUTS"
 
-  source $TARGET_SHORTCUTS
+  source "$TARGET_SHORTCUTS"
+
   _mod_.step "SHORTCUTS"
-  _mod_.msg_debug "Shortcuts file created in $TARGET_SHORTCUTS"
+  _mod_.msg_debug "Shortcuts file updated/created in $TARGET_SHORTCUTS"
 }
 
 # MMTodo:
